# Generated by Django 2.2 on 2021-05-18 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Car brand',
                'verbose_name_plural': 'Car brands',
            },
        ),
        migrations.CreateModel(
            name='CarFuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Car fuel',
                'verbose_name_plural': 'Car fuels',
            },
        ),
        migrations.CreateModel(
            name='CarOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Car Ownership',
                'verbose_name_plural': 'Car Ownerships',
            },
        ),
        migrations.CreateModel(
            name='CarTransmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Car transmission',
                'verbose_name_plural': 'Car transmissions',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=300)),
                ('kms_driven', models.IntegerField()),
                ('year', models.CharField(choices=[('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000'), ('1999', '1999'), ('1998', '1998'), ('1997', '1997'), ('1996', '1996'), ('1995', '1995'), ('Before 1995', 'Before 1995')], max_length=30)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='cars/')),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
                ('posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.CarBrand')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.CarFuel')),
                ('ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.CarOwnership')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.CarTransmission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
