# Generated by Django 2.2 on 2021-05-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='image',
            field=models.URLField(default=123),
            preserve_default=False,
        ),
    ]
