# Generated by Django 2.2 on 2021-06-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210523_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='kms_driven',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
