# Generated by Django 2.2 on 2021-04-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='image',
            field=models.ImageField(default=2021, upload_to='bikes/'),
            preserve_default=False,
        ),
    ]
