# Generated by Django 2.2 on 2021-05-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_bike_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='brand',
            field=models.CharField(blank=True, choices=[('Royal Enfield', 'Royal Enfield'), ('Yamaha', 'Yamaha'), ('Bajaj', 'Bajaj'), ('Hero', 'Hero'), ('Honda', 'Honda'), ('TVS', 'TVS'), ('Suzuki', 'Suzuki'), ('Java', 'Java'), ('KTM', 'KTM'), ('Hero Electric', 'Hero Electric'), ('Ampere', 'Ampere'), ('Aprilla', 'Aprilla'), ('Ather', 'Ather'), ('Avanturaa Choppers', 'Avanturaa Choppers'), ('Benling', 'Benling'), ('Benelli', 'Benelli'), ('BGauss', 'BGauss'), ('BMW', 'BMW'), ('CFMoto', 'CFMoto'), ('Ducati', 'Ducati'), ('Eeve', 'Eeve'), ('Evolet', 'Evolet'), ('F.B Mondial', 'F.B Mondial'), ('Gemopai', 'Gemopai'), ('Harley-Davidson', 'Harley-Davidson'), ('Husqvarna', 'Husqvarna'), ('Hyosung', 'Hyosung'), ('Indian', 'Indian'), ('Joy-e-bike', 'Joy-e-bike'), ('Kawasaki', 'Kawasaki'), ('Lectro', 'Lectro'), ('Mahindra', 'Mahindra'), ('Moto Guzzi', 'Moto Guzzi'), ('MV Augusta', 'MV Augusta'), ('Norton', 'Norton'), ('Odysse', 'Odysse'), ('Okinawa', 'Okinawa'), ('PURE EV', 'PURE EV'), ('Revolt', 'Revolt'), ('SWM', 'SWM'), ('Techo Electra', 'Techo Electra'), ('Triumph', 'Triumph'), ('Vespa', 'Vespa'), ('Yo', 'Yo'), ('Other Brands', 'Other Brands')], max_length=200),
        ),
        migrations.AddField(
            model_name='bike',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='bike',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='year',
            field=models.CharField(blank=True, choices=[('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000'), ('1999', '1999'), ('1998', '1998'), ('1997', '1997'), ('1996', '1996'), ('1995', '1995'), ('Before 1995', 'Before 1995')], max_length=5),
        ),
    ]
