# Generated by Django 2.2 on 2021-05-05 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_auto_20210505_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
