# Generated by Django 2.2 on 2021-05-12 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0008_auto_20210510_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='brands',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
