# Generated by Django 2.2 on 2021-06-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0012_auto_20210523_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='kms_driven',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bike',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
